BOARD_DIFFICULTY_EASY = 0
BOARD_DIFFICULTY_MEDIUM = 1
BOARD_DIFFICULTY_HARD = 2

BOARD_DIR_OCLOCK = 0
BOARD_DIR_COUNTEROCLOCK = 1

MOVE_DIR_RIGHT = 0
MOVE_DIR_DOWN = 1
MOVE_DIR_LEFT = 2
MOVE_DIR_UP = 3

CELL_TYPE_SPACE = 1
CELL_TYPE_STATION = 2
CELL_TYPE_OBSTACLE = 3

CELL_SPACE = 0
CELL_STATION_TITAN = 1
CELL_STATION_SAKAAR = 2
CELL_STATION_EGO = 3
CELL_STATION_ASGARD = 4
CELL_STATION_XANDAR = 5
CELL_OBSTACLE_DEBRIS = 6
CELL_OBSTACLE_METEORITE = 7
CELL_OBSTACLE_ASTEROID = 8
CELL_OBSTACLE_COSMIC_RAD = 9
CELL_OBSTACLE_SOLAR_RAD = 10